// Derives every rendering of the brand marks from the sources in `brand/`.
//
//   brand/wordmark.mjs      -> brand/wordmark.svg           reference artwork
//   + brand/logo-symbol*.svg   brand/lockup.svg             reference artwork
//                              brand/lockup-white.svg       reference artwork
//                              src/wordmarkGeometry.ts      bundled by the app
//                              src/symbolGeometry.ts        bundled by the app
//                              marketing/assets/logo-symbol.svg  the website's mark
//                              marketing/partials/brand.html     the header lockup
//
// The last two belong to the marketing site, which lives in a separate website
// repository now — `marketing/` is gitignored and kept only to seed it. They are
// written there rather than into `public/`, so running this script cannot put an
// asset the app never references back into every instance's Build_Output.
//
// `scripts/gen-og.mjs` imports `brand/lockup.mjs` directly, so the card needs
// nothing generated. Nothing else hand-copies path data or proportions: run
// `npm run brand` after touching the letterforms or the symbol and every output
// moves together.
//
// The symbol variants themselves are hand-authored sources. This script only
// ever reads and copies them.
import { copyFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { wordmarkGeometry, wordmarkSvg, WORDMARK_TEXT } from "../brand/wordmark.mjs";
import { lockupMetrics, lockupSvg, SYMBOL_TO_CAP, GAP_TO_CAP } from "../brand/lockup.mjs";
import { loadSymbol } from "../brand/symbol.mjs";

const root = new URL("../", import.meta.url);
const geo = wordmarkGeometry();

/** Cap height the marketing header sets the lockup at, in px. */
const HEADER_CAP = 15;

const abs = (rel) => fileURLToPath(new URL(rel, root));
const write = (rel, contents) => {
  writeFileSync(abs(rel), contents);
  const lines = contents.split("\n").length;
  console.log(`wrote ${rel} (${lines} line${lines === 1 ? "" : "s"})`);
};

// --- Reference artwork ------------------------------------------------------
// Not shipped. These are the files to open in a vector editor to look at the
// marks. The white lockup is the one to reach for on a solid green or
// terracotta ground.
const GENERATED = "Generated by scripts/gen-brand.mjs. Edit the brand/*.mjs sources instead.";

write("brand/wordmark.svg", `<!-- ${GENERATED} -->\n${wordmarkSvg({ ink: "#2d5d4d" })}\n`);
write("brand/lockup.svg", `<!-- ${GENERATED} -->\n${lockupSvg({ capHeight: 72, ink: "#2d5d4d" })}\n`);
write(
  "brand/lockup-white.svg",
  `<!-- ${GENERATED} The white symbol and a white wordmark, for solid grounds. -->\n` +
    `${lockupSvg({ capHeight: 72, variant: "white", ink: "#ffffff" })}\n`
);

// --- The website's served mark ----------------------------------------------
// Only the coloured symbol is copied out: it is the one the marketing header
// renders. The white and black variants stay sources — the Open Graph card
// inlines the white one at generation time rather than fetching it.
//
// The app does not use any of them: it draws its badge from `src/AppIcon.tsx` and
// the generated icons in `public/`. So this lands in `marketing/assets/`, with the
// header partial below it, rather than in the app's `public/`.
copyFileSync(abs("brand/logo-symbol.svg"), abs("marketing/assets/logo-symbol.svg"));
console.log("wrote marketing/assets/logo-symbol.svg (copied verbatim)");

// --- Marketing header -------------------------------------------------------
// Both pieces carry explicit width/height so the header reserves the right box
// before the CSS arrives — the brand sits above the fold and must not shift
// (Req 15.3). `.brand` centres them, which lands the symbol on the wordmark's
// cap band because the wordmark's box is padded to be symmetric about it.
const m = lockupMetrics(HEADER_CAP);

// `width`/`height` on an <img> must be valid non-negative integers — the HTML
// spec says so, and the marketing budget test enforced it before that suite left
// with the site — while the lockup
// metrics are fractional. Rounding the symbol's box costs 0.04px of width at
// this size, a 0.1% deviation from the artwork's aspect ratio, which is well
// under a device pixel. The wordmark is an inline <svg>, where fractional
// dimensions are legal, so it keeps its exact box.
const imgWidth = Math.round(m.symbol.width);
const imgHeight = Math.round(m.symbol.height);

write(
  "marketing/partials/brand.html",
  [
    `<!-- ${GENERATED}`,
    "     The symbol is decorative, so alt is empty (Req 10.4); the wordmark",
    "     beside it supplies the brand link's accessible name, which is why it",
    '     carries role="img" and a label. The gap between them is set by',
    `     \`.brand { gap }\` in marketing.css and wants ${m.gap}px at this size. -->`,
    `<img`,
    `  class="brand-mark"`,
    `  src="/logo-symbol.svg"`,
    `  alt=""`,
    `  width="${imgWidth}"`,
    `  height="${imgHeight}"`,
    `  loading="eager"`,
    `  decoding="async"`,
    `/>`,
    wordmarkSvg({
      className: "brand-wordmark",
      ariaLabel: WORDMARK_TEXT,
      attrs: `width="${m.wordmark.width}" height="${m.wordmark.height}"`,
    }),
    "",
  ].join("\n")
);

// --- App bundle -------------------------------------------------------------
write(
  "src/wordmarkGeometry.ts",
  [
    "// Generated by scripts/gen-brand.mjs from brand/wordmark.mjs. Do not edit.",
    "//",
    "// Committed rather than generated at build time so the app bundle carries no",
    "// dependency on the brand directory or on a build step running first.",
    "",
    "/**",
    " * The layout box. Padded so it sits symmetrically about the cap band, which",
    " * makes centring the wordmark against other content correct by default —",
    " * see the note in brand/wordmark.mjs.",
    " */",
    `export const WORDMARK_VIEW_BOX = ${JSON.stringify(geo.viewBox)};`,
    "",
    "/** Layout box width / height. Multiply a height by this to get its width. */",
    `export const WORDMARK_ASPECT = ${geo.aspect};`,
    "",
    "/** Cap height as a fraction of the box height, for optical sizing. */",
    `export const WORDMARK_CAP_RATIO = ${geo.capRatio};`,
    "",
    "/** Stroke weight, in viewBox units. */",
    `export const WORDMARK_STROKE = ${geo.strokeWidth};`,
    "",
    "export const WORDMARK_PATHS: readonly string[] = [",
    ...geo.paths.map((d) => `  ${JSON.stringify(d)},`),
    "];",
    "",
  ].join("\n")
);

// The symbol the app bundle carries, alongside the wordmark it already had, so
// the splash and the sign-in screen show the real mark instead of a stand-in
// glyph. The *white* variant is the one extracted: a single flat fill is what can
// be repainted, so the component drops the fills and inherits `currentColor` the
// way the icon set does. The coloured variant's two fills cannot reduce to one,
// which is exactly what `loadSymbol` refuses to guess at.
const symbol = loadSymbol({ variant: "white" });
const symbolPaths = [...symbol.inner.matchAll(/<path\b[^>]*\bd="([^"]+)"/g)].map((m) => m[1]);

// `symbolGeometry.ts` renders the paths and nothing else, so anything in the
// artwork that is not a `<path>` would be silently dropped. Fail instead: a
// `<circle>` or a gradient added to the source has to be handled here on purpose.
const leftovers = symbol.inner.replace(/<path\b[^>]*\/>/g, "").replace(/\s+/g, "");
if (leftovers !== "") {
  throw new Error(
    `brand/${symbol.file} holds markup other than <path> elements (${leftovers.slice(0, 60)}…); ` +
      `src/symbolGeometry.ts cannot represent it`
  );
}

write(
  "src/symbolGeometry.ts",
  [
    "// Generated by scripts/gen-brand.mjs from brand/logo-symbol-white.svg. Do not edit.",
    "//",
    "// Committed rather than generated at build time, for the same reason as",
    "// wordmarkGeometry.ts: the app bundle carries no dependency on the brand",
    "// directory or on a build step running first. Inlined rather than fetched from",
    "// public/ because the splash is the first thing a first run paints and must not",
    "// wait on a request to draw the mark.",
    "//",
    "// The paths carry no fill, so `src/LogoSymbol.tsx` can paint them with",
    "// `currentColor` — this is the white (single-fill) variant with the fill",
    "// dropped, not the two-colour mark.",
    "",
    "/** The artwork's own box. The ink fills it edge to edge, with no padding. */",
    `export const SYMBOL_VIEW_BOX = ${JSON.stringify(
      `${symbol.minX} ${symbol.minY} ${symbol.width} ${symbol.height}`
    )};`,
    "",
    "/** Box width / height. Multiply a height by this to get its width. */",
    `export const SYMBOL_ASPECT = ${Math.round(symbol.aspect * 1e6) / 1e6};`,
    "",
    "export const SYMBOL_PATHS: readonly string[] = [",
    ...symbolPaths.map((d) => `  ${JSON.stringify(d)},`),
    "];",
    "",
  ].join("\n")
);

console.log(
  `\n${WORDMARK_TEXT}: ${geo.paths.length} subpaths, ink ${geo.width}x${geo.inkHeight}, ` +
    `layout box ${geo.width}x${geo.height}, cap ${(geo.capRatio * 100).toFixed(1)}% of box` +
    `\nsymbol: ${symbolPaths.length} paths, box ${symbol.width}x${symbol.height}` +
    `\nlockup: symbol ${SYMBOL_TO_CAP}x cap, gap ${GAP_TO_CAP}x cap` +
    ` — at cap ${HEADER_CAP}px that is ${m.symbol.width}x${m.symbol.height} + ${m.gap} + ` +
    `${m.wordmark.width}x${m.wordmark.height}, box ${m.width}x${m.height}`
);
