// Derives every rendering of the brand marks from the sources in `brand/`.
//
//   brand/wordmark.mjs      -> brand/wordmark.svg           reference artwork
//   + brand/logo-symbol*.svg   brand/lockup.svg             reference artwork
//                              brand/lockup-white.svg       reference artwork
//                              public/logo-symbol.svg       served to the header
//                              marketing/partials/brand.html the header lockup
//                              src/wordmarkGeometry.ts      bundled by the app
//
// `scripts/gen-og.mjs` imports `brand/lockup.mjs` directly, so the card needs
// nothing generated. Nothing else hand-copies path data or proportions: run
// `npm run brand` after touching the letterforms or the symbol and every output
// moves together.
//
// The symbol variants themselves are hand-authored sources. This script only
// ever reads and copies them.
import { copyFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { wordmarkGeometry, wordmarkSvg, WORDMARK_TEXT } from "../brand/wordmark.mjs";
import { lockupMetrics, lockupSvg, SYMBOL_TO_CAP, GAP_TO_CAP } from "../brand/lockup.mjs";

const root = new URL("../", import.meta.url);
const geo = wordmarkGeometry();

/** Cap height the marketing header sets the lockup at, in px. */
const HEADER_CAP = 15;

const abs = (rel) => fileURLToPath(new URL(rel, root));
const write = (rel, contents) => {
  writeFileSync(abs(rel), contents);
  const lines = contents.split("\n").length;
  console.log(`wrote ${rel} (${lines} line${lines === 1 ? "" : "s"})`);
};

// --- Reference artwork ------------------------------------------------------
// Not shipped. These are the files to open in a vector editor to look at the
// marks. The white lockup is the one to reach for on a solid green or
// terracotta ground.
const GENERATED = "Generated by scripts/gen-brand.mjs. Edit the brand/*.mjs sources instead.";

write("brand/wordmark.svg", `<!-- ${GENERATED} -->\n${wordmarkSvg({ ink: "#2d5d4d" })}\n`);
write("brand/lockup.svg", `<!-- ${GENERATED} -->\n${lockupSvg({ capHeight: 72, ink: "#2d5d4d" })}\n`);
write(
  "brand/lockup-white.svg",
  `<!-- ${GENERATED} The white symbol and a white wordmark, for solid grounds. -->\n` +
    `${lockupSvg({ capHeight: 72, variant: "white", ink: "#ffffff" })}\n`
);

// --- Served assets ----------------------------------------------------------
// Only the coloured symbol ships: it is the one the marketing header renders.
// The white and black variants stay sources — the Open Graph card inlines the
// white one at build time rather than fetching it, so shipping a copy would add
// dead weight to every install's precache.
copyFileSync(abs("brand/logo-symbol.svg"), abs("public/logo-symbol.svg"));
console.log("wrote public/logo-symbol.svg (copied verbatim)");

// --- Marketing header -------------------------------------------------------
// Both pieces carry explicit width/height so the header reserves the right box
// before the CSS arrives — the brand sits above the fold and must not shift
// (Req 15.3). `.brand` centres them, which lands the symbol on the wordmark's
// cap band because the wordmark's box is padded to be symmetric about it.
const m = lockupMetrics(HEADER_CAP);

// `width`/`height` on an <img> must be valid non-negative integers — the HTML
// spec says so and marketing.budget.test.ts enforces it — while the lockup
// metrics are fractional. Rounding the symbol's box costs 0.04px of width at
// this size, a 0.1% deviation from the artwork's aspect ratio, which is well
// under a device pixel. The wordmark is an inline <svg>, where fractional
// dimensions are legal, so it keeps its exact box.
const imgWidth = Math.round(m.symbol.width);
const imgHeight = Math.round(m.symbol.height);

write(
  "marketing/partials/brand.html",
  [
    `<!-- ${GENERATED}`,
    "     The symbol is decorative, so alt is empty (Req 10.4); the wordmark",
    "     beside it supplies the brand link's accessible name, which is why it",
    '     carries role="img" and a label. The gap between them is set by',
    `     \`.brand { gap }\` in marketing.css and wants ${m.gap}px at this size. -->`,
    `<img`,
    `  class="brand-mark"`,
    `  src="/logo-symbol.svg"`,
    `  alt=""`,
    `  width="${imgWidth}"`,
    `  height="${imgHeight}"`,
    `  loading="eager"`,
    `  decoding="async"`,
    `/>`,
    wordmarkSvg({
      className: "brand-wordmark",
      ariaLabel: WORDMARK_TEXT,
      attrs: `width="${m.wordmark.width}" height="${m.wordmark.height}"`,
    }),
    "",
  ].join("\n")
);

// --- App bundle -------------------------------------------------------------
write(
  "src/wordmarkGeometry.ts",
  [
    "// Generated by scripts/gen-brand.mjs from brand/wordmark.mjs. Do not edit.",
    "//",
    "// Committed rather than generated at build time so the app bundle carries no",
    "// dependency on the brand directory or on a build step running first.",
    "",
    "/**",
    " * The layout box. Padded so it sits symmetrically about the cap band, which",
    " * makes centring the wordmark against other content correct by default —",
    " * see the note in brand/wordmark.mjs.",
    " */",
    `export const WORDMARK_VIEW_BOX = ${JSON.stringify(geo.viewBox)};`,
    "",
    "/** Layout box width / height. Multiply a height by this to get its width. */",
    `export const WORDMARK_ASPECT = ${geo.aspect};`,
    "",
    "/** Cap height as a fraction of the box height, for optical sizing. */",
    `export const WORDMARK_CAP_RATIO = ${geo.capRatio};`,
    "",
    "/** Stroke weight, in viewBox units. */",
    `export const WORDMARK_STROKE = ${geo.strokeWidth};`,
    "",
    "export const WORDMARK_PATHS: readonly string[] = [",
    ...geo.paths.map((d) => `  ${JSON.stringify(d)},`),
    "];",
    "",
  ].join("\n")
);

console.log(
  `\n${WORDMARK_TEXT}: ${geo.paths.length} subpaths, ink ${geo.width}x${geo.inkHeight}, ` +
    `layout box ${geo.width}x${geo.height}, cap ${(geo.capRatio * 100).toFixed(1)}% of box` +
    `\nlockup: symbol ${SYMBOL_TO_CAP}x cap, gap ${GAP_TO_CAP}x cap` +
    ` — at cap ${HEADER_CAP}px that is ${m.symbol.width}x${m.symbol.height} + ${m.gap} + ` +
    `${m.wordmark.width}x${m.wordmark.height}, box ${m.width}x${m.height}`
);
