// Generated by scripts/gen-brand.mjs from brand/wordmark.mjs. Do not edit.
//
// Committed rather than generated at build time so the app bundle carries no
// dependency on the brand directory or on a build step running first.

/**
 * The layout box. Padded so it sits symmetrically about the cap band, which
 * makes centring the wordmark against other content correct by default —
 * see the note in brand/wordmark.mjs.
 */
export const WORDMARK_VIEW_BOX = "0 -26 507.07 152";

/** Layout box width / height. Multiply a height by this to get its width. */
export const WORDMARK_ASPECT = 3.336;

/** Cap height as a fraction of the box height, for optical sizing. */
export const WORDMARK_CAP_RATIO = 0.6579;

/** Stroke weight, in viewBox units. */
export const WORDMARK_STROKE = 20;

export const WORDMARK_PATHS: readonly string[] = [
  "M43.97 17.35A18.68 20.75 0 0 0 21.28 10.2A18.68 20.75 0 0 0 10.39 33.45A18.68 20.75 0 0 0 28.67 50A18.68 20.75 0 0 1 46.96 66.55A18.68 20.75 0 0 1 36.07 89.8A18.68 20.75 0 0 1 13.38 82.65",
  "M72.35 90L72.35 58A21.5 21.5 0 0 1 93.85 36.5A21.5 21.5 0 0 1 115.35 58L115.35 90",
  "M141.35 64A27.5 27.5 0 0 1 168.85 36.5A27.5 27.5 0 0 1 196.35 64A27.5 27.5 0 0 1 168.85 91.5A27.5 27.5 0 0 1 141.35 64Z",
  "M196.35 38L196.35 90",
  "M225.35 64A27.5 27.5 0 0 1 252.85 36.5A27.5 27.5 0 0 1 280.35 64A27.5 27.5 0 0 1 252.85 91.5A27.5 27.5 0 0 1 225.35 64Z",
  "M225.35 38L225.35 116",
  "M346.21 50L373.07 50A34.86 41.5 0 0 1 347.23 90.09A34.86 41.5 0 0 1 308.02 70.75A34.86 41.5 0 0 1 313.56 20.66A34.86 41.5 0 0 1 355.64 14.06",
  "M397.07 38L397.07 70A21.5 21.5 0 0 0 418.57 91.5A21.5 21.5 0 0 0 440.07 70L440.07 38",
  "M481.07 22L481.07 74A16 16 0 0 0 497.07 90",
  "M466.07 38L497.07 38",
];
